#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Package an EloqDoc install prefix as a TiUP cluster component tarball.

The input prefix is the release install directory generated by the TiKV/CentOS7
build flow, for example:

  install/tikv-centos7/
    bin/eloqdoc
    bin/eloqdoc-cli
    bin/host_manager
    lib/*.so*

The produced TiUP cluster package intentionally keeps that prefix under a
top-level "eloqdoc/" directory:

  eloqdoc/bin/eloqdoc
  eloqdoc/bin/eloqdoc-cli
  eloqdoc/bin/host_manager
  eloqdoc/bin/launch_sv
  eloqdoc/lib/...

TiUP cluster extracts packages into <deploy_dir>/bin, so the deployed runtime
prefix becomes <deploy_dir>/bin/eloqdoc. This preserves the binaries'
existing $ORIGIN/../lib RUNPATH and mirrors the "component subdir carries its
runtime libraries" pattern used by TiFlash.

Usage:
  scripts/package-eloqdoc-tiup.sh [options]

Options:
  --prefix DIR          EloqDoc install prefix (default: install/tikv-centos7)
  --host-manager FILE   host_manager executable (default: <prefix>/bin/host_manager)
  --launch-sv FILE      launch_sv executable (default: src/mongo/db/modules/eloq/data_substrate/eloq_log_service/bld/launch_sv)
  --version VERSION     Package version (default: parsed from eloqdoc --version, e.g. v0.2.6)
  --os OS               Target OS in TiUP package name (default: linux)
  --arch ARCH           Target arch in TiUP package name (default: amd64; x86_64 is normalized)
  --component NAME      TiUP component name (default: eloqdoc)
  --output-dir DIR      Output directory (default: dist/tiup)
  --install-to-cache    Copy the package to ~/.tiup/storage/cluster/packages
  --cache-version VER   Version to use in the cache filename (default: --version; use "nightly" for local manifest-free tests)
  --dry-run             Validate and print the planned package layout without creating a tarball
  -h, --help            Show this help

Examples:
  # Build a normal package:
  scripts/package-eloqdoc-tiup.sh --prefix install/tikv-centos7 --version v0.2.6

  # Local TiUP cluster test without publishing a signed mirror manifest:
  scripts/package-eloqdoc-tiup.sh --prefix install/tikv-centos7 --version v0.2.6 \
    --install-to-cache --cache-version nightly
  # Then set component_versions.eloqdoc: nightly in topology.yaml.
EOF
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
prefix="$repo_root/install/tikv-centos7"
host_manager_path=""
launch_sv_path=""
version=""
target_os="linux"
target_arch="amd64"
component="eloqdoc"
output_dir="$repo_root/dist/tiup"
install_to_cache=0
cache_version=""
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      prefix="$2"
      shift 2
      ;;
    --host-manager)
      host_manager_path="$2"
      shift 2
      ;;
    --launch-sv)
      launch_sv_path="$2"
      shift 2
      ;;
    --version)
      version="$2"
      shift 2
      ;;
    --os)
      target_os="$2"
      shift 2
      ;;
    --arch)
      target_arch="$2"
      shift 2
      ;;
    --component)
      component="$2"
      shift 2
      ;;
    --output-dir)
      output_dir="$2"
      shift 2
      ;;
    --install-to-cache)
      install_to_cache=1
      shift
      ;;
    --cache-version)
      cache_version="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$target_arch" in
  x86_64) target_arch="amd64" ;;
  aarch64) target_arch="arm64" ;;
esac

prefix="$(cd "$prefix" && pwd)"
eloqdoc_bin="$prefix/bin/eloqdoc"
eloqdoc_cli="$prefix/bin/eloqdoc-cli"
if [[ -z "$host_manager_path" ]]; then
  host_manager_bin="$prefix/bin/host_manager"
else
  host_manager_bin="$host_manager_path"
fi
if [[ -z "$launch_sv_path" ]]; then
  launch_sv_bin="$repo_root/src/mongo/db/modules/eloq/data_substrate/eloq_log_service/bld/launch_sv"
else
  launch_sv_bin="$launch_sv_path"
fi
lib_dir="$prefix/lib"

abs_existing_path() {
  local p="$1"
  if [[ -e "$p" ]]; then
    (cd "$(dirname "$p")" && printf '%s/%s\n' "$PWD" "$(basename "$p")")
  else
    printf '%s\n' "$p"
  fi
}

host_manager_bin="$(abs_existing_path "$host_manager_bin")"
launch_sv_bin="$(abs_existing_path "$launch_sv_bin")"

if [[ ! -x "$eloqdoc_bin" ]]; then
  echo "missing executable: $eloqdoc_bin" >&2
  exit 1
fi
if [[ ! -x "$eloqdoc_cli" ]]; then
  echo "missing executable: $eloqdoc_cli" >&2
  exit 1
fi
if [[ ! -x "$host_manager_bin" ]]; then
  echo "missing executable: $host_manager_bin" >&2
  exit 1
fi
if [[ ! -x "$launch_sv_bin" ]]; then
  echo "missing executable: $launch_sv_bin" >&2
  exit 1
fi
if [[ ! -d "$lib_dir" ]]; then
  echo "missing library directory: $lib_dir" >&2
  exit 1
fi

if [[ -z "$version" ]]; then
  version="$(
    LD_LIBRARY_PATH="$lib_dir:${LD_LIBRARY_PATH:-}" "$eloqdoc_bin" --version 2>/dev/null |
      awk '/^db version / {print $3; exit}'
  )"
fi
if [[ -z "$version" ]]; then
  echo "failed to determine version; pass --version explicitly" >&2
  exit 1
fi
if [[ "$version" != v* && "$version" != "nightly" ]]; then
  version="v$version"
fi
if [[ -z "$cache_version" ]]; then
  cache_version="$version"
fi

ensure_origin_runpath() {
  local binary="$1"
  local label="$2"
  local origin_runpath='$ORIGIN/../lib'

  if ! command -v readelf >/dev/null 2>&1; then
    echo "cannot validate RPATH/RUNPATH for $label: readelf is not available" >&2
    exit 1
  fi

  if readelf -d "$binary" | grep -E 'RPATH|RUNPATH' | grep -Fq "$origin_runpath"; then
    return
  fi

  if ! command -v patchelf >/dev/null 2>&1; then
    echo "cannot set RPATH/RUNPATH for $label: patchelf is not available" >&2
    echo "expected $origin_runpath so TiUP deployments can resolve eloqdoc/lib" >&2
    exit 1
  fi

  local old_runpath new_runpath
  old_runpath="$(patchelf --print-rpath "$binary" 2>/dev/null || true)"
  new_runpath="$origin_runpath"
  if [[ -n "$old_runpath" ]]; then
    new_runpath="$origin_runpath:$old_runpath"
  fi
  patchelf --set-rpath "$new_runpath" "$binary"

  if ! readelf -d "$binary" | grep -E 'RPATH|RUNPATH' | grep -Fq "$origin_runpath"; then
    echo "RPATH/RUNPATH validation failed for $label: expected $origin_runpath" >&2
    readelf -d "$binary" | grep -E 'RPATH|RUNPATH' >&2 || true
    exit 1
  fi
}

check_runtime_dependencies() {
  if ! command -v ldd >/dev/null 2>&1; then
    echo "warning: skip runtime dependency check because ldd is not available" >&2
    return
  fi

  local failed=0
  for binary in "$@"; do
    if ldd "$binary" | grep -q 'not found'; then
      echo "runtime dependency check failed for $binary: ldd reports missing libraries" >&2
      ldd "$binary" >&2 || true
      failed=1
    fi
  done
  if [[ "$failed" -ne 0 ]]; then
    exit 1
  fi
}

package_name="${component}-${version}-${target_os}-${target_arch}.tar.gz"
cache_package_name="${component}-${cache_version}-${target_os}-${target_arch}.tar.gz"
output_path="$output_dir/$package_name"
tiup_home="${TIUP_HOME:-$HOME/.tiup}"
cluster_cache="$tiup_home/storage/cluster/packages/$cache_package_name"

echo "EloqDoc prefix:      $prefix"
echo "Component:           $component"
echo "Version:             $version"
echo "Platform:            $target_os/$target_arch"
echo "Package:             $output_path"
if [[ "$install_to_cache" -eq 1 ]]; then
  echo "TiUP cluster cache:  $cluster_cache"
fi
echo "Package layout:"
echo "  eloqdoc/bin/eloqdoc"
echo "  eloqdoc/bin/eloqdoc-cli"
echo "  eloqdoc/bin/host_manager"
echo "  eloqdoc/bin/launch_sv"
echo "  eloqdoc/lib/..."

stage="$(mktemp -d "${TMPDIR:-/tmp}/eloqdoc-tiup-package.XXXXXX")"
cleanup() {
  rm -rf "$stage"
}
trap cleanup EXIT

mkdir -p "$stage/eloqdoc/bin" "$stage/eloqdoc/lib"
cp -a "$eloqdoc_bin" "$eloqdoc_cli" "$host_manager_bin" "$launch_sv_bin" "$stage/eloqdoc/bin/"
cp -a "$lib_dir"/. "$stage/eloqdoc/lib/"

staged_binaries=(
  "$stage/eloqdoc/bin/eloqdoc"
  "$stage/eloqdoc/bin/eloqdoc-cli"
  "$stage/eloqdoc/bin/host_manager"
  "$stage/eloqdoc/bin/launch_sv"
)
for binary in "${staged_binaries[@]}"; do
  ensure_origin_runpath "$binary" "eloqdoc/bin/$(basename "$binary")"
done
check_runtime_dependencies "${staged_binaries[@]}"

if [[ "$dry_run" -eq 1 ]]; then
  echo "Dry run successful; staged dependency and RPATH checks passed."
  exit 0
fi

mkdir -p "$output_dir"
tar -C "$stage" -czf "$output_path" eloqdoc
echo "Created $output_path"

if [[ "$install_to_cache" -eq 1 ]]; then
  mkdir -p "$(dirname "$cluster_cache")"
  cp -f "$output_path" "$cluster_cache"
  echo "Installed cache package $cluster_cache"
fi
