name: test-clang-format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './src/mongo/db/modules/eloq'
        extensions: 'h,cpp'
        clangFormatVersion: 18
        style: file
